export function parseLayoutConfigDto(str: string): LayoutConfigDto;
export const DefaultLayoutConfigDto: LayoutConfigDto;
export type LengthDto = import("../Shared/Length.js").LengthDto;
export type TextConfigDto = import("../Drawing/TextConfig.js").TextConfigDto;
export type TextConfig = import("../Drawing/TextConfig.js").TextConfig;
export type LayoutConfigDto = {
    lyricTextConfig: TextConfigDto;
    chorusTextConfig: TextConfigDto;
    refTextConfig: TextConfigDto;
    titleTextConfig: TextConfigDto;
    chordTextConfig: TextConfigDto;
    unifyChords?: boolean | undefined;
    printPageNumbers: boolean;
    firstPage?: ("left" | "right") | undefined;
    tableOfContents?: string | undefined;
    outerMargin: LengthDto;
    innerMargin: LengthDto;
    topMargin: LengthDto;
    bottomMargin: LengthDto;
    pageWidth: LengthDto;
    pageHeight: LengthDto;
    sectionDistance: LengthDto;
};
export type LayoutConfig = {
    lyricTextConfig: TextConfig;
    chorusTextConfig: TextConfig;
    refTextConfig: TextConfig;
    titleTextConfig: TextConfig;
    chordTextConfig: TextConfig;
    unifyChords: boolean;
    printPageNumbers: boolean;
    firstPage: "left" | "right";
    tableOfContents: string;
    outerMargin: Length;
    innerMargin: Length;
    topMargin: Length;
    bottomMargin: Length;
    pageWidth: Length;
    pageHeight: Length;
    sectionDistance: Length;
};
import { Length } from "../Index.js";
