export function renderSingleFile(path: string, outPath: string, layoutConfigDto: LayoutConfigDto, debug: boolean): Promise<void>;
export function renderAllInSingleFile(paths: string[], outPath: string, layoutConfigDto: LayoutConfigDto, debug: boolean): Promise<void>;
export function renderSongAsPdf(songs: Song[], debug: boolean, layoutConfig: LayoutConfig, pdfDoc: PDFDocument): Promise<Uint8Array>;
export type PDFPage = import("pdf-lib").PDFPage;
export type SongSection = import("../Song/Song.js").SongSection;
export type Box = import("../Drawing/Geometry.js").Box;
export type LayoutConfig = import("./LayoutConfig.js").LayoutConfig;
export type LayoutConfigDto = import("./LayoutConfig.js").LayoutConfigDto;
export type RectangleGenerator = import("../Drawing/Geometry.js").RectangleGenerator;
export type ChordConfig = import("./ChordBox.js").ChordConfig;
export type Dims = import("../Drawing/Geometry.js").Dimensions;
export type LengthDto = import("../Shared/Length.js").LengthDto;
export type TextConfigDto = import("../Drawing/TextConfig.js").TextConfigDto;
import { Song } from "../Song/Song.js";
import { PDFDocument } from "pdf-lib";
